import resend
from datetime import datetime
from config import FROM_EMAIL, TO_EMAILS_LIST, RESEND_API_KEY, TIMEZONE


class EmailService:
    def __init__(self):
        """Initialize the email service with Resend API key"""
        if RESEND_API_KEY:
            resend.api_key = RESEND_API_KEY
            self.enabled = True
        else:
            self.enabled = False
            print("⚠️ Email service disabled - RESEND_API_KEY not configured")

    def is_configured(self):
        """Check if email service is properly configured"""
        return (self.enabled and 
                FROM_EMAIL and 
                TO_EMAILS_LIST and 
                RESEND_API_KEY)

    async def send_async_updates_email(self, bot):
        """Send email with async updates only"""
        if not self.is_configured():
            print("⚠️ Email service not configured - skipping async updates email")
            return False

        try:
            # Generate email content
            subject, html_content, text_content = self._generate_email_content(bot)
            
            # Send email
            params = {
                "from": FROM_EMAIL,
                "to": TO_EMAILS_LIST,
                "subject": subject,
                "html": html_content,
                "text": text_content,
            }
            
            email = resend.Emails.send(params)
            print(f"✅ Async updates email sent successfully! ID: {email['id']}")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send async updates email: {e}")
            return False

    def _generate_email_content(self, bot):
        """Generate HTML and text content for the dev team updates email"""
        now = datetime.now(TIMEZONE)
        date_str = now.strftime("%A, %B %d, %Y")
        
        # Generate subject
        subject = f"Daily Dev Team Updates - {date_str}"
        
        # Check if there are any async updates
        if not bot.tracker.async_updates_today:
            # No async updates case
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <title>Daily Dev Team Updates</title>
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }}
                    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px; }}
                    .header h1 {{ margin: 0; font-size: 24px; }}
                    .header p {{ margin: 10px 0 0 0; opacity: 0.9; }}
                    .no-updates {{ background: #f8f9fa; padding: 30px; border-radius: 8px; text-align: center; color: #6c757d; }}
                    .footer {{ text-align: center; color: #6c757d; font-size: 14px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e9ecef; }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>👥 Daily Dev Team Updates</h1>
                    <p>{date_str}</p>
                </div>
                
                <div class="no-updates">
                    <h3>No team updates submitted today</h3>
                    <p>All team members participated in the voice standup.</p>
                </div>
                
                <div class="footer">
                    <p>Generated by Discord Standup Bot</p>
                </div>
            </body>
            </html>
            """
            
            text_content = f"""
DAILY DEV TEAM UPDATES
{date_str}

No team updates submitted today.
All team members participated in the voice standup.

Generated by Discord Standup Bot
            """
            
            return subject, html_content, text_content
        
        # Generate HTML content for team updates
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Daily Dev Team Updates</title>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
                .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 30px; }}
                .header h1 {{ margin: 0; font-size: 24px; }}
                .header p {{ margin: 10px 0 0 0; opacity: 0.9; }}
                .summary {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 30px; text-align: center; }}
                .summary h2 {{ color: #495057; margin-top: 0; }}
                .count {{ font-size: 32px; font-weight: bold; color: #28a745; margin: 10px 0; }}
                .team-update {{ background: white; padding: 20px; margin: 15px 0; border-radius: 8px; border-left: 4px solid #28a745; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
                .team-update .author {{ font-weight: bold; color: #495057; font-size: 18px; margin-bottom: 5px; }}
                .team-update .time {{ color: #6c757d; font-size: 14px; margin-bottom: 10px; }}
                .team-update .message {{ color: #333; line-height: 1.5; }}
                .footer {{ text-align: center; color: #6c757d; font-size: 14px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e9ecef; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>👥 Daily Dev Team Updates</h1>
                <p>{date_str}</p>
            </div>
            
            <div class="summary">
                <h2>Team Updates Submitted</h2>
                <div class="count">{len(bot.tracker.async_updates_today)}</div>
            </div>
        """
        
        # Add team updates
        for user_id, data in bot.tracker.async_updates_today.items():
            html_content += f"""
            <div class="team-update">
                <div class="author">{data['name']}</div>
                <div class="time">Posted at {data['time']}</div>
                <div class="message">{data['message']}</div>
            </div>
            """
        
        html_content += """
            <div class="footer">
                <p>Generated by Discord Standup Bot</p>
            </div>
        </body>
        </html>
        """
        
        # Generate text content
        text_content = f"""
DAILY DEV TEAM UPDATES
{date_str}

Team Updates Submitted: {len(bot.tracker.async_updates_today)}

"""
        
        for user_id, data in bot.tracker.async_updates_today.items():
            text_content += f"{data['name']} (Posted at {data['time']})\n"
            text_content += f"{data['message']}\n\n"
        
        text_content += "Generated by Discord Standup Bot"
        
        return subject, html_content, text_content
